#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x5F,0x6F,0xE7,0x08,0x1E,0x95,
   
    };
static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0x5F,0x6F,0xE7,0x26,0x45,0x8E
                          
  };
#endif // BITCOIN_CHAINPARAMSSEEDS_H
